Feat: reset password
CartONG/plateforme-urbaine-cameroun pull request #47
Opened 2024-12-06 21:57 UTC by yvalentin

2024-12-18 14:50 UTC, plduthoit requested changes
Je pense que c'est bon. Il y avait quelques conflits avec main. J'ai du remettre la branche a jour avec main, vu qu'il y avait 18000 changements..
J'ai essayé résoudre les conflits. Les fichiers de trad étaient tout remis en ordre alphabétiques, un peu l'horreur pour résoudre les conflits.
Du coup peux être a surveiller si tes trads sont toujours là.. Et vérifier que la page Mon compte s'affiche bien.


De mon côté j'arrive pas à tester la fonctionnalité en local.
J'ai un
```
Connection could not be established with host "localhost:25": stream_socket_client(): Unable to connect to localhost:25 (Connection refused)
```

Des trucs à ajuster ? des trucs a mettre dans un .env 

Sinon pour le reste des micros commentaires, mais ça m'a l'air bon 👌

2024-12-18 14:50 UTC, plduthoit commented on symfony/config/packages/mailer.yaml
> +            sender: 'no-reply@cartong.org'
Je l'aurais bien mis dans une variable d'environnement celui là peux être.

2024-12-18 14:50 UTC, plduthoit commented on symfony/config/packages/translation.yaml
> +        providers:
cool!

2024-12-18 14:50 UTC, plduthoit commented on vue/src/views/auth/AuthForgotPassword.vue
> +  await router.replace({
pourquoi un `await` ici.

2024-12-18 14:50 UTC, plduthoit commented on vue/src/views/auth/AuthResetPasswordOk.vue
> +      <router-link append :to="{ query: { ...$route.query, dialog: DialogKey.AUTH_SIGN_IN } }">
cool le append

2024-12-20 15:09 UTC, yvalentin commented on symfony/config/packages/mailer.yaml
> +            sender: 'no-reply@cartong.org'
Oui ! J'ai fait ça dans la branche de verification d'email? Mais je change ici
Merci

2024-12-20 15:15 UTC, yvalentin commented on vue/src/views/auth/AuthForgotPassword.vue
> +  await router.replace({
Parce que route.replace renvoie une Promise
```ts
replace(to: RouteLocationRaw): Promise<NavigationFailure | void | undefined>;
```
Mais aà part, mon IDE qui me signale un warning sans le await ! Ca n'est certainement pas obligatoire.
Ca doit dépendre du comportement attendu

> Remember you can await router.replace() if you need to wait for the new route to be displayed.
https://router.vuejs.org/guide/advanced/dynamic-routing.html#Adding-routes

2024-12-20 15:37 UTC, yvalentin commented
J'ai ajouter la config par défaut pour le mailer... Ca devrait être bon maintenant ;-)

2025-01-14 21:42 UTC, merged